// Copyright (C) 2021-Present CITEC Inc. <https://citecsolutions.com/>
// All rights reserved
//
// This file is part of CITEC Inc. source code.
// This software framework contains the confidential and proprietary information
// of CITEC Inc., its affiliates, and its licensors. Your use of these
// materials is governed by the terms of the Agreement between your organisation
// and CITEC Inc., and any unauthorised use is forbidden. Except as otherwise
// stated in the Agreement, this software framework is for your internal use
// only and may only be shared outside your organisation with the prior written
// permission of CITEC Inc.
// CITEC Inc. source code can not be copied and/or distributed without the express
// permission of CITEC Inc.
import '@testing-library/jest-dom'
import { buildDataIdeas } from 'features/ideas/positions'

// intercept the useAuth0 function and mock it
jest.mock('@auth0/auth0-react', () => ({
    Auth0Provider: ({ children }: { children: any }) => children,
    withAuthenticationRequired: (component: any) => component,
    useAuth0: () => {
        return {
            isLoading: false,
            user: { sub: 'foobar' },
            isAuthenticated: true,
            loginWithRedirect: jest.fn(),
        }
    },
}))


test('loadPortfolioOnRedux', () => {
    const ideas = [
        {
            portfolio_id: 25,
            portfolio: "portfolio Russel 1000",
            benchmark: "IWD",
            creation_date: "2022-06-24 16:50:33",
            ticker: [
                "VG",
                "EGP",
                "BKH",
                "TGNA",
                "PNM",
                "STAG",
                "HR",
                "ASGN",
                "CCMP",
                "NSA",
                "OGS",
                "HOMB",
                "OMCL",
                "AMKR",
                "ONB",
                "TNET",
                "THC",
                "MGY",
                "SSB",
                "AMN",
                "HGV",
                "CAR",
                "HLI",
                "ESNT",
                "UMBF",
                "BL",
                "MUSA",
                "OVV",
                "UBSI",
                "CMC",
                "EME",
                "IIVI",
                "UUUU",
                "CHK",
                "RRC",
                "COKE",
                "AMC",
                "SLAB",
                "PFGC",
                "IRT",
                "DOCN"
            ],
            outstanding_balance: [
                435385.07,
                364721.98,
                346642.39,
                332876.22,
                316068.35,
                241952.98,
                174186.1,
                173530.74,
                170943.99,
                158451.74,
                154019.8,
                145366.18,
                137624.48,
                132650.79,
                132401.76,
                121291.91,
                116140.76,
                110502.56,
                100844.41,
                95908.53,
                90268.04,
                88320.27,
                86645,
                77842.88,
                76064.76,
                69898.8,
                63226.41,
                53560.27,
                51660.62,
                51417.39,
                45623.33,
                34564.8,
                30091.21,
                28947.36,
                28554.08,
                21807.83,
                18153.65,
                14269.67,
                13342.69,
                6863.42,
                6003.78
            ],
            unrealized_capital_gains: [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            optimization_status: null
        }
    ]

    const positions = [
        {
            ticker: "VG",
            status: "OK",
            isin: "US92886T2015",
            figi: "BBG000BRB5D9",
            name: "Vonage Holdings Corp",
            ipo: "2006-05-24",
            sector: "Information Technology",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/VG/quote",
            url_company: "https://www.vonage.com/",
            url_logo: "https://static.finnhub.io/logo/97da4736-80ec-11ea-9d1d-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "EGP",
            status: "OK",
            isin: "US2772761019",
            figi: "BBG000BHRBT4",
            name: "Eastgroup Properties Inc",
            ipo: "1980-03-17",
            sector: "Real Estate",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/EGP/quote",
            url_company: "https://www.eastgroup.net/",
            url_logo: "https://static.finnhub.io/logo/cae96998-80eb-11ea-b735-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "BKH",
            status: "OK",
            isin: "US0921131092",
            figi: "BBG000BD9ZM7",
            name: "Black Hills Corp",
            ipo: "1980-03-17",
            sector: "Utilities",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/BKH/quote",
            url_company: "https://www.blackhillscorp.com/",
            url_logo: "https://static.finnhub.io/logo/89f3132c-80eb-11ea-85ef-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "TGNA",
            status: "OK",
            isin: "US87901J1051",
            figi: "BBG000BK5DP1",
            name: "Tegna Inc",
            ipo: "1969-03-10",
            sector: "Communication Services",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/TGNA/quote",
            url_company: "http://www.tegna.com/",
            url_logo: "https://static.finnhub.io/logo/e6bc3a14-80eb-11ea-a64a-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "PNM",
            status: "OK",
            isin: "US69349H1077",
            figi: "BBG000BRDFF3",
            name: "PNM Resources Inc",
            ipo: "1980-03-17",
            sector: "Utilities",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/PNM/quote",
            url_company: "https://www.pnmresources.com/",
            url_logo: "https://static.finnhub.io/logo/a6e5ba35fa6ae867c0271d40fbe453a1c8372edb10ebc08a64ffa1a9b45c65e6.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "STAG",
            status: "OK",
            isin: "US85254J1025",
            figi: "BBG000BGLFP7",
            name: "STAG Industrial Inc",
            ipo: "2011-04-15",
            sector: "Real Estate",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/STAG/quote",
            url_company: "http://www.stagindustrial.com/",
            url_logo: "https://static.finnhub.io/logo/80746240-80c9-11ea-af84-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "HR",
            status: "OK",
            isin: "US4219461047",
            figi: "BBG000BB67F4",
            name: "Healthcare Realty Trust Inc",
            ipo: "1993-05-27",
            sector: "Real Estate",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/HR/quote",
            url_company: "https://www.healthcarerealty.com/",
            url_logo: "https://static.finnhub.io/logo/1f26a08cb6b705692f90aaa50def1ca5e6c9d9348c1592e7582726dd4cc96b89.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "ASGN",
            status: "OK",
            isin: "US00191U1025",
            figi: "BBG000CRN8N8",
            name: "ASGN Inc",
            ipo: "1982-09-16",
            sector: "Industrials",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/ASGN/quote",
            url_company: "https://www.asgn.com/",
            url_logo: "https://static.finnhub.io/logo/acdf1e42-80df-11ea-850e-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "CCMP",
            status: "OK",
            isin: "US12571T1007",
            figi: "BBG000BP3NW2",
            name: "CMC Materials Inc",
            ipo: "2000-04-04",
            sector: "Information Technology",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/CCMP/quote",
            url_company: "https://www.cmcmaterials.com/company/who-we-are/default.aspx",
            url_logo: "https://static.finnhub.io/logo/bfbefb22-80df-11ea-bdff-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "NSA",
            status: "OK",
            isin: "US6378701063",
            figi: "BBG008417VN4",
            name: "National Storage Affiliates Trust",
            ipo: "2015-04-23",
            sector: "Real Estate",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/NSA/quote",
            url_company: "https://www.nationalstorageaffiliates.com/",
            url_logo: "https://static.finnhub.io/logo/7bcb8c38-80d1-11ea-aa3a-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "OGS",
            status: "OK",
            isin: "US68235P1084",
            figi: "BBG004WQKD07",
            name: "ONE Gas Inc",
            ipo: "2014-01-16",
            sector: "Utilities",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/OGS/quote",
            url_company: "http://www.onegas.com/",
            url_logo: "https://static.finnhub.io/logo/592a5d6c-80cf-11ea-852d-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "HOMB",
            status: "OK",
            isin: "US4368932004",
            figi: "BBG000QJXDW9",
            name: "Home BancShares Inc",
            ipo: "2006-06-23",
            sector: "Financials",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/HOMB/quote",
            url_company: "https://www.homebancshares.com",
            url_logo: "https://static.finnhub.io/logo/f4820964-826a-11ea-ba27-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "OMCL",
            status: "OK",
            isin: "US68213N1090",
            figi: "BBG000BTNGZ4",
            name: "Omnicell Inc",
            ipo: "2001-08-08",
            sector: "Health Care",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/OMCL/quote",
            url_company: "https://www.omnicell.com/",
            url_logo: "https://static.finnhub.io/logo/8f20a7e2-80e0-11ea-9abc-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "AMKR",
            status: "OK",
            isin: "US0316521006",
            figi: "BBG000BCKGW7",
            name: "Amkor Technology Inc",
            ipo: "1998-05-01",
            sector: "Information Technology",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/AMKR/quote",
            url_company: "https://www.amkor.com/",
            url_logo: "https://static.finnhub.io/logo/6dcd7482-826a-11ea-8de4-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "ONB",
            status: "OK",
            isin: "US6800331075",
            figi: "BBG000KFW1C2",
            name: "Old National Bancorp",
            ipo: "1984-06-20",
            sector: "Financials",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/ONB/quote",
            url_company: "http://ir.oldnational.com/",
            url_logo: "https://static.finnhub.io/logo/4b370692-80ec-11ea-806f-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "TNET",
            status: "OK",
            isin: "US8962881079",
            figi: "BBG000BR2040",
            name: "TriNet Group Inc",
            ipo: "2014-03-27",
            sector: "Industrials",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/TNET/quote",
            url_company: "https://www.trinet.com/",
            url_logo: "https://static.finnhub.io/logo/7dafc07a-80cf-11ea-bf82-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "THC",
            status: "OK",
            isin: "US88033G4073",
            figi: "BBG000CPHYL4",
            name: "Tenet Healthcare Corp",
            ipo: "1981-05-22",
            sector: "Health Care",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/THC/quote",
            url_company: "https://www.tenethealth.com/",
            url_logo: "https://static.finnhub.io/logo/84ddafda-80ec-11ea-bf20-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "MGY",
            status: "OK",
            isin: "US5596631094",
            figi: "BBG00GNC8DL2",
            name: "Magnolia Oil & Gas Corp",
            ipo: "2017-06-26",
            sector: "Energy",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/MGY/quote",
            url_company: "https://www.tpg.com/pace-energy",
            url_logo: "https://static.finnhub.io/logo/f0ad9d0534c857f7acfcdfc3bec56904f08ca33faaefd9eaa107055d41e34df1.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "SSB",
            status: "OK",
            isin: "US8404411097",
            figi: "BBG000BNPYN9",
            name: "SouthState Corp",
            ipo: "1997-01-28",
            sector: "Financials",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/SSB/quote",
            url_company: "https://southstatecorporation.q4ir.com/",
            url_logo: "https://static.finnhub.io/logo/96975fe6954d890260f6e583d89be96b81f17fe4fc9b1ecbb09e5215784c49ad.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "AMN",
            status: "OK",
            isin: "US0017441017",
            figi: "BBG000BCT197",
            name: "AMN Healthcare Services Inc",
            ipo: "2001-11-13",
            sector: "Health Care",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/AMN/quote",
            url_company: "https://www.amnhealthcare.com/",
            url_logo: "https://static.finnhub.io/logo/794762e4590c19d96df0a1e7c70c1cf670b7ab871b7d9766714b45bc205ab512.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "HGV",
            status: "OK",
            isin: "US43283X1054",
            figi: "BBG00CBYY6M1",
            name: "Hilton Grand Vacations Inc",
            ipo: "2016-12-13",
            sector: "Consumer Discretionary",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/HGV/quote",
            url_company: "https://www.hiltongrandvacations.com/",
            url_logo: "https://static.finnhub.io/logo/e51af146-80db-11ea-8e19-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "CAR",
            status: "OK",
            isin: "US0537741052",
            figi: "BBG000FLPRH1",
            name: "Avis Budget Group Inc",
            ipo: "1983-09-15",
            sector: "Industrials",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/CAR/quote",
            url_company: "http://www.avisbudgetgroup.com/",
            url_logo: "https://static.finnhub.io/logo/7cdcd459da25c1b59c152d4825a093418aadef817860d120aef7387ffdc59978.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "HLI",
            status: "OK",
            isin: "US4415931009",
            figi: "BBG000CZTB66",
            name: "Houlihan Lokey Inc",
            ipo: "2015-08-13",
            sector: "Financials",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/HLI/quote",
            url_company: "https://hl.com/",
            url_logo: "https://static.finnhub.io/logo/b6c8736015a76367d88c141361231e14c81f276c2542bd90cc3cdb96593e97cf.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "ESNT",
            status: "OK",
            isin: "BMG3198U1027",
            figi: "BBG0058YL7G9",
            name: "Essent Group Ltd",
            ipo: "2013-10-31",
            sector: "Financials",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/ESNT/quote",
            url_company: "http://essentgroup.com/",
            url_logo: "https://static.finnhub.io/logo/128c5f30-81b2-11ea-bc3d-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "UMBF",
            status: "OK",
            isin: "US9027881088",
            figi: "BBG000DD8WX1",
            name: "UMB Financial Corp",
            ipo: "1980-03-17",
            sector: "Financials",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/UMBF/quote",
            url_company: "https://investorrelations.umb.com/overview/corporate-profile/",
            url_logo: "https://static.finnhub.io/logo/d89cbef8-80e0-11ea-bef7-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "BL",
            status: "OK",
            isin: "US09239B1098",
            figi: "BBG0029KJVB0",
            name: "Blackline Inc",
            ipo: "2016-10-28",
            sector: "Information Technology",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/BL/quote",
            url_company: "https://www.blackline.com/",
            url_logo: "https://static.finnhub.io/logo/f033b8a2-80db-11ea-a1ad-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "MUSA",
            status: "OK",
            isin: "US6267551025",
            figi: "BBG001Z0Q6T5",
            name: "Murphy Usa Inc",
            ipo: "2013-08-19",
            sector: "Consumer Discretionary",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/MUSA/quote",
            url_company: "https://www.murphyusa.com/",
            url_logo: "https://static.finnhub.io/logo/7b9b4bf0-80ce-11ea-9e75-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "OVV",
            status: "OK",
            isin: "US69047Q1022",
            figi: "BBG00R2NHQ65",
            name: "Ovintiv Inc",
            ipo: "2001-08-21",
            sector: "Energy",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/OVV/quote",
            url_company: "https://www.ovintiv.com/",
            url_logo: "https://static.finnhub.io/logo/d86f436c92676d71b5b37fcb6c8db8ad082e4cc0dfbc6d8e40287aa184302acc.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "UBSI",
            status: "OK",
            isin: "US9099071071",
            figi: "BBG000BVXC87",
            name: "United Bankshares Inc",
            ipo: "1970-09-16",
            sector: "Financials",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/UBSI/quote",
            url_company: "https://www.ubsi-inc.com/",
            url_logo: "https://static.finnhub.io/logo/1ddc8941a9e3771b95ea7eef484089829481639edd77faf23a3af79cc0499046.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "CMC",
            status: "OK",
            isin: "US2017231034",
            figi: "BBG000BFSND8",
            name: "Commercial Metals Co",
            ipo: "1981-05-22",
            sector: "Materials",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/CMC/quote",
            url_company: "https://www.cmc.com",
            url_logo: "https://static.finnhub.io/logo/a22fd99e-80eb-11ea-aca7-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "EME",
            status: "OK",
            isin: "US29084Q1004",
            figi: "BBG000BBRPL4",
            name: "EMCOR Group Inc",
            ipo: "2000-11-16",
            sector: "Industrials",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/EME/quote",
            url_company: "https://www.emcorgroup.com/",
            url_logo: "https://static.finnhub.io/logo/ccee9f24-80eb-11ea-bc25-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "IIVI",
            status: "OK",
            isin: "US9021041085",
            figi: "BBG000BLW102",
            name: "II-VI Inc",
            ipo: "1987-10-13",
            sector: "Information Technology",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/IIVI/quote",
            url_company: "https://www.ii-vi.com/",
            url_logo: "https://static.finnhub.io/logo/2b23661502919208876abc1bba33237d6468bd44c337633ef6c4ea7776da2103.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "UUUU",
            status: "OK",
            isin: "CA2926717083",
            figi: "BBG000BXTPV3",
            name: "Energy Fuels Inc",
            ipo: "1988-03-04",
            sector: "Energy",
            url_morningstar: "https://www.morningstar.com/stocks/xase/UUUU/quote",
            url_company: "http://www.energyfuels.com/",
            url_logo: "https://static.finnhub.io/logo/6b9b9088-80f3-11ea-bcf7-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "CHK",
            status: "OK",
            isin: "US1651677353",
            figi: "BBG00Z6DX554",
            name: "Chesapeake Energy Corp",
            ipo: "2021-02-09",
            sector: "Energy",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/CHK/quote",
            url_company: "http://www.chk.com/",
            url_logo: "https://static.finnhub.io/logo/0a557519ba98591cc2ffbd81a981b795ecf305e00f9e6e941a37541ff783a1af.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "RRC",
            status: "OK",
            isin: "US75281A1097",
            figi: "BBG000FVXD63",
            name: "Range Resources Corp",
            ipo: "1996-10-11",
            sector: "Energy",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/RRC/quote",
            url_company: "http://www.rangeresources.com/",
            url_logo: "https://static.finnhub.io/logo/674bdbae-80ec-11ea-bf4b-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "COKE",
            status: "OK",
            isin: "US1910981026",
            figi: "BBG000BG1SX2",
            name: "Coca-Cola Consolidated Inc",
            ipo: "1972-05-10",
            sector: "Consumer Staples",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/COKE/quote",
            url_company: "https://www.cokeconsolidated.com/",
            url_logo: "https://static.finnhub.io/logo/c1f9e6ac-80df-11ea-9d6c-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "AMC",
            status: "OK",
            isin: "US00165C1045",
            figi: "BBG000TDCVT6",
            name: "AMC Entertainment Holdings Inc",
            ipo: "2013-12-18",
            sector: "Communication Services",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/AMC/quote",
            url_company: "https://investor.amctheatres.com/",
            url_logo: "https://static.finnhub.io/logo/b485766c-80ce-11ea-ad69-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "SLAB",
            status: "OK",
            isin: "US8269191024",
            figi: "BBG000BB99S3",
            name: "Silicon Laboratories Inc",
            ipo: "2000-03-24",
            sector: "Information Technology",
            url_morningstar: "https://www.morningstar.com/stocks/xnas/SLAB/quote",
            url_company: "https://www.silabs.com/",
            url_logo: "https://static.finnhub.io/logo/af48f3e4-80e0-11ea-82b0-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "PFGC",
            status: "OK",
            isin: "US71377A1034",
            figi: "BBG009XW2WB8",
            name: "Performance Food Group Co",
            ipo: "2015-10-01",
            sector: "Consumer Staples",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/PFGC/quote",
            url_company: "http://www.pfgc.com/",
            url_logo: "https://static.finnhub.io/logo/5a5b3f06-80d2-11ea-a904-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "IRT",
            status: "OK",
            isin: "US45378A1060",
            figi: "BBG004Q00KS7",
            name: "Independence Realty Trust Inc",
            ipo: "2013-08-13",
            sector: "Real Estate",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/IRT/quote",
            url_company: "https://www.irtliving.com/",
            url_logo: "https://static.finnhub.io/logo/bf8150e2-81b1-11ea-829c-00000000092a.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        },
        {
            ticker: "DOCN",
            status: "OK",
            isin: "US25402D1028",
            figi: "BBG00ZGF6SS3",
            name: "DigitalOcean Holdings Inc",
            ipo: "2021-03-24",
            sector: "Information Technology",
            url_morningstar: "https://www.morningstar.com/stocks/xnys/DOCN/quote",
            url_company: "",
            url_logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/DOCN.png",
            outstanding_balance: 0,
            unrealized_capital_gains: 0
        }
    ]

    buildDataIdeas(ideas, positions)
})

