// Copyright (C) 2021-Present CITEC Inc. <https://citecsolutions.com/>
// All rights reserved
//
// This file is part of CITEC Inc. source code.
// This software framework contains the confidential and proprietary information
// of CITEC Inc., its affiliates, and its licensors. Your use of these
// materials is governed by the terms of the Agreement between your organisation
// and CITEC Inc., and any unauthorised use is forbidden. Except as otherwise
// stated in the Agreement, this software framework is for your internal use
// only and may only be shared outside your organisation with the prior written
// permission of CITEC Inc.
// CITEC Inc. source code can not be copied and/or distributed without the express
// permission of CITEC Inc.
import '@testing-library/jest-dom'
import {
   getStockForValidation,
   getTypeStock,
   buildDataInvest,
} from 'features/brokers/alpaca/utils/positions-alpaca-utils'

describe('test in Position Alpaca', () => {
   test('getStockForValidation', () => {
      const arg = [
         {
            asset_id: '72356e3a-8792-4928-a1e8-b626bdc17b59',
            symbol: 'QYLD',
            exchange: 'NASDAQ',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '5',
            avg_entry_price: '18.08',
            side: 'long',
            market_value: '87.05',
            cost_basis: '90.4',
            unrealized_pl: '-3.35',
            unrealized_plpc: '-0.0370575221238938',
            unrealized_intraday_pl: '0.1',
            unrealized_intraday_plpc: '0.0011500862564692',
            current_price: '17.41',
            lastday_price: '17.39',
            change_today: '0.0011500862564692',
            qty_available: '5',
         },
         {
            asset_id: '3a64306e-4a77-4a06-8458-15a8bfd31f55',
            symbol: 'VTI',
            exchange: 'ARCA',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '1',
            avg_entry_price: '207.4',
            side: 'long',
            market_value: '186.92',
            cost_basis: '207.4',
            unrealized_pl: '-20.48',
            unrealized_plpc: '-0.0987463837994214',
            unrealized_intraday_pl: '0',
            unrealized_intraday_plpc: '0',
            current_price: '186.92',
            lastday_price: '186.92',
            change_today: '0',
            qty_available: '1',
         },
         {
            asset_id: '64bbff51-59d6-4b3c-9351-13ad85e3c752',
            symbol: 'BTCUSD',
            exchange: 'FTXU',
            asset_class: 'crypto',
            asset_marginable: false,
            qty: '1',
            avg_entry_price: '29140.111',
            side: 'long',
            market_value: '21564',
            cost_basis: '29140.111',
            unrealized_pl: '-7576.111',
            unrealized_plpc: '-0.2599890920113516',
            unrealized_intraday_pl: '-577',
            unrealized_intraday_plpc: '-0.0260602502145341',
            current_price: '21564',
            lastday_price: '22141',
            change_today: '-0.0260602502145341',
            qty_available: '1',
         },
         {
            asset_id: '69b15845-7c63-4586-b274-1cfdfe9df3d8',
            symbol: 'GOOGL',
            exchange: 'NASDAQ',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '6',
            avg_entry_price: '2247.4116666666666667',
            side: 'long',
            market_value: '12906.06',
            cost_basis: '13484.47',
            unrealized_pl: '-578.41',
            unrealized_plpc: '-0.0428945297812966',
            unrealized_intraday_pl: '99.51',
            unrealized_intraday_plpc: '0.0077702425711843',
            current_price: '2151.01',
            lastday_price: '2134.31',
            change_today: '0.0078245428264872',
            qty_available: '6',
         },
         {
            asset_id: 'b0b6dd9d-8b9b-48a9-ba46-b9d54906e415',
            symbol: 'AAPL',
            exchange: 'NASDAQ',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '9',
            avg_entry_price: '144.0655555555555556',
            side: 'long',
            market_value: '1204.11',
            cost_basis: '1296.59',
            unrealized_pl: '-92.48',
            unrealized_plpc: '-0.0713255539530615',
            unrealized_intraday_pl: '9.27',
            unrealized_intraday_plpc: '0.007758360952094',
            current_price: '133.79',
            lastday_price: '132.76',
            change_today: '0.007758360952094',
            qty_available: '9',
         },
         {
            asset_id: 'b6d1aa75-5c9c-4353-a305-9e2caa1925ab',
            symbol: 'MSFT',
            exchange: 'NASDAQ',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '8',
            avg_entry_price: '251.125',
            side: 'long',
            market_value: '1974.4',
            cost_basis: '2009',
            unrealized_pl: '-34.6',
            unrealized_plpc: '-0.0172224987555998',
            unrealized_intraday_pl: '18.67',
            unrealized_intraday_plpc: '0.0095463075168863',
            current_price: '246.8',
            lastday_price: '244.49',
            change_today: '0.009448239191787',
            qty_available: '8',
         },
         {
            asset_id: '8ccae427-5dd0-45b3-b5fe-7ba5e422c766',
            symbol: 'TSLA',
            exchange: 'NASDAQ',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '5',
            avg_entry_price: '746.9',
            side: 'long',
            market_value: '3346.75',
            cost_basis: '3734.5',
            unrealized_pl: '-387.75',
            unrealized_plpc: '-0.1038291605301915',
            unrealized_intraday_pl: '33.4',
            unrealized_intraday_plpc: '0.010080432190985',
            current_price: '669.35',
            lastday_price: '662.67',
            change_today: '0.010080432190985',
            qty_available: '5',
         },
      ]

      const resSolv = ['QYLD', 'VTI', 'GOOGL', 'AAPL', 'MSFT', 'TSLA']
      const resp = getStockForValidation(arg)
      expect(resp).toEqual(resSolv)
   })
   test('getStatusStock', () => {
      const arg = [
         {
            ticker: 'QYLD',
            asset_type: 'ETP',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Global X Funds Global X NASDAQ 100 Covered Call ETF',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
         {
            ticker: 'VTI',
            asset_type: 'ETP',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Vanguard Total Stock Market ETF',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
         {
            ticker: 'GOOGL',
            asset_type: 'Common Stock',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Alphabet Inc',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
         {
            ticker: 'AAPL',
            asset_type: 'Common Stock',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Apple Inc',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
         {
            ticker: 'MSFT',
            asset_type: 'Common Stock',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Microsoft Corporation',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
         {
            ticker: 'TSLA',
            asset_type: 'Common Stock',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Tesla Inc',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
      ]

      const resp = getTypeStock('QYLD', arg)
      expect(resp).toEqual('ETP')
   })

   test('buildDataInvest', () => {
      const arg1 = [
         {
            asset_id: '72356e3a-8792-4928-a1e8-b626bdc17b59',
            symbol: 'QYLD',
            exchange: 'NASDAQ',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '5',
            avg_entry_price: '18.08',
            side: 'long',
            market_value: '87.05',
            cost_basis: '90.4',
            unrealized_pl: '-3.35',
            unrealized_plpc: '-0.0370575221238938',
            unrealized_intraday_pl: '0.1',
            unrealized_intraday_plpc: '0.0011500862564692',
            current_price: '17.41',
            lastday_price: '17.39',
            change_today: '0.0011500862564692',
            qty_available: '5',
         },
         {
            asset_id: '3a64306e-4a77-4a06-8458-15a8bfd31f55',
            symbol: 'VTI',
            exchange: 'ARCA',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '1',
            avg_entry_price: '207.4',
            side: 'long',
            market_value: '186.92',
            cost_basis: '207.4',
            unrealized_pl: '-20.48',
            unrealized_plpc: '-0.0987463837994214',
            unrealized_intraday_pl: '0',
            unrealized_intraday_plpc: '0',
            current_price: '186.92',
            lastday_price: '186.92',
            change_today: '0',
            qty_available: '1',
         },
         {
            asset_id: '69b15845-7c63-4586-b274-1cfdfe9df3d8',
            symbol: 'GOOGL',
            exchange: 'NASDAQ',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '6',
            avg_entry_price: '2247.4116666666666667',
            side: 'long',
            market_value: '12906.06',
            cost_basis: '13484.47',
            unrealized_pl: '-578.41',
            unrealized_plpc: '-0.0428945297812966',
            unrealized_intraday_pl: '99.51',
            unrealized_intraday_plpc: '0.0077702425711843',
            current_price: '2151.01',
            lastday_price: '2134.31',
            change_today: '0.0078245428264872',
            qty_available: '6',
         },
         {
            asset_id: 'b0b6dd9d-8b9b-48a9-ba46-b9d54906e415',
            symbol: 'AAPL',
            exchange: 'NASDAQ',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '9',
            avg_entry_price: '144.0655555555555556',
            side: 'long',
            market_value: '1204.11',
            cost_basis: '1296.59',
            unrealized_pl: '-92.48',
            unrealized_plpc: '-0.0713255539530615',
            unrealized_intraday_pl: '9.27',
            unrealized_intraday_plpc: '0.007758360952094',
            current_price: '133.79',
            lastday_price: '132.76',
            change_today: '0.007758360952094',
            qty_available: '9',
         },
         {
            asset_id: 'b6d1aa75-5c9c-4353-a305-9e2caa1925ab',
            symbol: 'MSFT',
            exchange: 'NASDAQ',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '8',
            avg_entry_price: '251.125',
            side: 'long',
            market_value: '1974.4',
            cost_basis: '2009',
            unrealized_pl: '-34.6',
            unrealized_plpc: '-0.0172224987555998',
            unrealized_intraday_pl: '18.67',
            unrealized_intraday_plpc: '0.0095463075168863',
            current_price: '246.8',
            lastday_price: '244.49',
            change_today: '0.009448239191787',
            qty_available: '8',
         },
         {
            asset_id: '8ccae427-5dd0-45b3-b5fe-7ba5e422c766',
            symbol: 'TSLA',
            exchange: 'NASDAQ',
            asset_class: 'us_equity',
            asset_marginable: true,
            qty: '5',
            avg_entry_price: '746.9',
            side: 'long',
            market_value: '3346.75',
            cost_basis: '3734.5',
            unrealized_pl: '-387.75',
            unrealized_plpc: '-0.1038291605301915',
            unrealized_intraday_pl: '33.4',
            unrealized_intraday_plpc: '0.010080432190985',
            current_price: '669.35',
            lastday_price: '662.67',
            change_today: '0.010080432190985',
            qty_available: '5',
         },
      ]

      const arg2 = [
         {
            ticker: 'QYLD',
            asset_type: 'ETP',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Global X Funds Global X NASDAQ 100 Covered Call ETF',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
         {
            ticker: 'VTI',
            asset_type: 'ETP',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Vanguard Total Stock Market ETF',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
         {
            ticker: 'GOOGL',
            asset_type: 'Common Stock',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Alphabet Inc',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
         {
            ticker: 'AAPL',
            asset_type: 'Common Stock',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Apple Inc',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
         {
            ticker: 'MSFT',
            asset_type: 'Common Stock',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Microsoft Corporation',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
         {
            ticker: 'TSLA',
            asset_type: 'Common Stock',
            status: 'OK',
            isin: null,
            figi: null,
            name: 'Tesla Inc',
            ipo: null,
            sector: null,
            market_cap: null,
            pe: null,
            pb: null,
            dividend_yield: null,
            url_morningstar: null,
            url_company: null,
            url_logo: null,
         },
      ]

      const respSol = [
         {
            asset_class: 'US Equities',
            quantity: 28,
            price: 0,
            investment: 19431.32,
            day_gain_loss: [160.85, 0.83],
            total_gain_loss: [-1093.24, -5.33],
            subRows: [
               {
                  asset_class: 'GOOGL',
                  quantity: '6',
                  price: '2151.01',
                  investment: '12906.06',
                  day_gain_loss: ['99.51', 0.78],
                  total_gain_loss: ['-578.41', -4.29],
                  url_logo: null,
               },
               {
                  asset_class: 'AAPL',
                  quantity: '9',
                  price: '133.79',
                  investment: '1204.11',
                  day_gain_loss: ['9.27', 0.78],
                  total_gain_loss: ['-92.48', -7.13],
                  url_logo: null,
               },
               {
                  asset_class: 'MSFT',
                  quantity: '8',
                  price: '246.8',
                  investment: '1974.4',
                  day_gain_loss: ['18.67', 0.95],
                  total_gain_loss: ['-34.6', -1.72],
                  url_logo: null,
               },
               {
                  asset_class: 'TSLA',
                  quantity: '5',
                  price: '669.35',
                  investment: '3346.75',
                  day_gain_loss: ['33.4', 1.01],
                  total_gain_loss: ['-387.75', -10.38],
                  url_logo: null,
               },
            ],
         },
         {
            asset_class: 'ETF',
            quantity: 6,
            price: 0,
            investment: 273.96999999999997,
            day_gain_loss: [0.1, 0.04],
            total_gain_loss: [-23.830000000000002, -8],
            subRows: [
               {
                  asset_class: 'QYLD',
                  quantity: '5',
                  price: '17.41',
                  investment: '87.05',
                  day_gain_loss: ['0.1', 0.12],
                  total_gain_loss: ['-3.35', -3.71],
                  url_logo: null,
               },
               {
                  asset_class: 'VTI',
                  quantity: '1',
                  price: '186.92',
                  investment: '186.92',
                  day_gain_loss: ['0', 0],
                  total_gain_loss: ['-20.48', -9.87],
                  url_logo: null,
               },
            ],
         },
      ]

      const resp = buildDataInvest(arg1, arg2)
      expect(resp).toEqual(respSol)
   })
})
